### ISSUE TITLE
Display paid total in PRO payment history summary

### ISSUE THREAD

**Issue by TheCrowned** [TheCrowned/Post-Pay-Counter#14]

**Comment by gooddaytoday** [comment]
It will be good to display total payment for author with additional information: total visits of all author's posts. 

Why? Cause it's handy to up concrete author's revenue according to he/she total visits. Example: 

1. Start revenue fo athors is 1$ for 1k visits
2. Author reached total 3000 visits on all posts -> upping his revenue to 1.1$ for 1k
3. Author reached total 5000 visits on all posts -> upping his revenue to 1.2$ for 1k
...

**Comment by TheCrowned** [comment]
I see your point, and will keep this in (higher) consideration for future releases :)

**Comment by TheCrowned** [comment]
Included in PRO version 1.9 :)
