### ISSUE TITLE
Pay Per Symbols/Words & Pay Per Visits for publishing Editors

### ISSUE THREAD

**Issue by gooddaytoday** [TheCrowned/Post-Pay-Counter#22]
Is it doable to create Pay Per Symbols/Words & Pay Per Visits for publishing Editors? Now they can get fixed revenue, whatever is the size of publishing article (Pay Per Symbols) or its value (Pay Per Visits)

**Comment by TheCrowned** [comment]
I think the most flexible way would be to calculate their earning as a percentage of the payment for the post they have edited. Otherwise it's going to be too specific. What do you think?

**Comment by gooddaytoday** [comment]
Sounds great! And in such way responsability for quality doesn't pass to editors much.

**Comment by TheCrowned** [comment]
> And in such way responsability for quality doesn't pass to editors much.
Could you elaborate some more on this?

**Comment by gooddaytoday** [comment]
It is about who is Do the work: author or editor.

If we pay for words to editors (just for their written text), it shifts authors not to work enough and  shirk. And we'll end with editors, who do more work, than authors.

**Comment by TheCrowned** [comment]
Oh right, so you would imagine the payment to be split among the two, not to generate another payment? For example, if a post is shown to be worth $10 before any review, and you set the publisher to have 10% of the revenue, would you pay $9 to the author and 1$ to the editor, or $10 to the author and $1 to the editor?

**Comment by gooddaytoday** [comment]
10$ and 1$. And not only before review, but for all payments to author. Example:

Author revenue:
10$ for text and 10$ for visitors during 12 months = 20$ whole (10 after publishing and 10 after visitors for 12 months)

Editor 10% revenue:
1$ for publishing and 1 for visitors of 12 months = 2$.

?

**Comment by TheCrowned** [comment]
> 10$ and 1$. 
That's what I thought, good!

> And not only before review, but for all payments to author.
This is going to be difficult. We'll see :)

**Comment by TheCrowned** [comment]
Added bonus for each payment criteria @0204001. Will ship with Publisher Bonus version 1.3.
